### ISSUE TITLE
Fresh Install Django failed 

### ISSUE THREAD

**Issue by Zwordi** [cdr-stats/cdr-stats#45]
Hello,

Thanks for your tools .

I'm trying to setup cdrstats on a new debian but the results is that i don't have the django server running.

This is what i got from the setup.

reate CDR-Stats database...
sudo -u postgres createdb cdrstats_db
Create Postgresql user cdr_stats_43409
sudo -u postgres psql --command="create user cdr_stats_43409 with password 'XXXXXXXXXXXX';"
CREATE ROLE
Create CDR-Pusher database...
sudo -u postgres createdb cdr-pusher
Grant all privileges to user...
GRANT
GRANT
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
[3;J

Create a super admin user...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Install Bower deps
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Collects the static files
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/cdrstats/cdr/models.py", line 18, in <module>
    from postgres.fields import json_field
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/__init__.py", line 4, in <module>
    from .range_fields import Int4RangeField    # NOQA
  File "/opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/postgres/fields/range_fields.py", line 6, in <module>
    from django.db.models.sql import aggregates
ImportError: cannot import name aggregates
[ ok ] Stopping supervisor (via systemctl): supervisor.service.
[ ok ] Starting supervisor (via systemctl): supervisor.service.
Install Logrotate...
rm: cannot remove ‘/etc/logrotate.d/cdr_stats’: No such file or directory

Add Nginx configuration for Welcome page...

This will install CDR-Stats Backend, Celery & Redis on your server
Press Enter to continue or CTRL-C to exit

Install Redis-server ...
OK
Ign http://ftp.belnet.be jessie InRelease
Hit http://ftp.belnet.be jessie-updates InRelease                                                                                                              
Hit http://security.debian.org jessie/updates InRelease                                                                                                         
Hit http://packages.dotdeb.org jessie InRelease                                                                                                                 
Hit http://ftp.belnet.be jessie Release.gpg                                                                                                                     
Hit http://ftp.belnet.be jessie Release                                                                                 
Hit http://apt.postgresql.org jessie-pgdg InRelease                                               
Hit http://ftp.belnet.be jessie-updates/main Sources                                              
Hit http://ftp.us.debian.org jessie-backports InRelease                 
Hit http://ftp.belnet.be jessie-updates/contrib Sources                  
Hit http://ftp.belnet.be jessie-updates/non-free Sources                 
Get:1 http://ftp.belnet.be jessie-updates/main amd64 Packages/DiffIndex [5,440 B]
Hit http://ftp.belnet.be jessie-updates/contrib amd64 Packages                       
Get:2 http://ftp.belnet.be jessie-updates/non-free amd64 Packages/DiffIndex [736 B]
Hit http://ftp.belnet.be jessie-updates/contrib Translation-en           
Get:3 http://ftp.belnet.be jessie-updates/main Translation-en/DiffIndex [2,704 B]
Get:4 http://ftp.belnet.be jessie-updates/non-free Translation-en/DiffIndex [736 B]
Hit http://security.debian.org jessie/updates/main Sources                             
Hit http://security.debian.org jessie/updates/contrib Sources       
Hit http://security.debian.org jessie/updates/non-free Sources        
Hit http://packages.dotdeb.org jessie/all Sources                     
Hit http://security.debian.org jessie/updates/main amd64 Packages                                               
Hit http://ftp.belnet.be jessie/main Sources                                                                    
Hit http://ftp.belnet.be jessie/contrib Sources                                                                 
Hit http://ftp.belnet.be jessie/non-free Sources                                               
Hit http://ftp.belnet.be jessie/main amd64 Packages                                                           
Hit http://packages.dotdeb.org jessie/all amd64 Packages                                                      
Hit http://ftp.belnet.be jessie/contrib amd64 Packages                                  
Hit http://ftp.belnet.be jessie/non-free amd64 Packages                                 
Hit http://ftp.belnet.be jessie/contrib Translation-en                                       
Hit http://security.debian.org jessie/updates/contrib amd64 Packages                         
Hit http://security.debian.org jessie/updates/non-free amd64 Packages                                              
Hit http://security.debian.org jessie/updates/contrib Translation-en                                               
Hit http://security.debian.org jessie/updates/main Translation-en                                                                                                    
Hit http://ftp.belnet.be jessie/main Translation-en                                                                                                                  
Hit http://ftp.belnet.be jessie/main Translation-fr                                                                                                                  
Hit http://ftp.belnet.be jessie/non-free Translation-en                                                                                                        
Hit http://security.debian.org jessie/updates/non-free Translation-en                                                                                          
Hit http://apt.postgresql.org jessie-pgdg/main amd64 Packages                                                                            
Ign http://packages.dotdeb.org jessie/all Translation-en_US       
Ign http://packages.dotdeb.org jessie/all Translation-en                                                             
Ign http://packages.dotdeb.org jessie/all Translation-en_US.UTF-8                                                    
Ign http://packages.dotdeb.org jessie/all Translation-fr                                                             
Get:5 http://ftp.us.debian.org jessie-backports/main amd64 Packages/DiffIndex [27.8 kB]                              
Get:6 http://ftp.us.debian.org jessie-backports/main Translation-en/DiffIndex [27.8 kB]
Hit https://deb.nodesource.com jessie InRelease
Hit https://deb.nodesource.com jessie/main Sources                   
Ign http://apt.postgresql.org jessie-pgdg/main Translation-en_US
Hit https://deb.nodesource.com jessie/main amd64 Packages                
Ign http://apt.postgresql.org jessie-pgdg/main Translation-en         
Ign http://apt.postgresql.org jessie-pgdg/main Translation-en_US.UTF-8
Ign http://apt.postgresql.org jessie-pgdg/main Translation-fr
Get:7 https://deb.nodesource.com jessie/main Translation-en_US [162 B]
Get:8 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:9 https://deb.nodesource.com jessie/main Translation-en_US.UTF-8 [162 B]
Get:10 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Get:11 https://deb.nodesource.com jessie/main Translation-en_US [162 B]
Get:12 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:13 https://deb.nodesource.com jessie/main Translation-en_US.UTF-8 [162 B]
Get:14 https://deb.nodesource.com jessie/main Translation-fr [162 B]   
Get:15 https://deb.nodesource.com jessie/main Translation-en_US [162 B]
Get:16 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:17 https://deb.nodesource.com jessie/main Translation-en_US.UTF-8 [162 B]
Get:18 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Get:19 https://deb.nodesource.com jessie/main Translation-en_US [162 B]
Get:20 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:21 https://deb.nodesource.com jessie/main Translation-en_US.UTF-8 [162 B]
Get:22 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Get:23 https://deb.nodesource.com jessie/main Translation-en_US [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en_US
Get:24 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
Get:25 https://deb.nodesource.com jessie/main Translation-en_US.UTF-8 [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en_US.UTF-8
Get:26 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Ign https://deb.nodesource.com jessie/main Translation-fr
Fetched 65.2 kB in 4s (15.1 kB/s)        
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
redis-server is already the newest version.
The following packages were automatically installed and are no longer required:
  libc-ares2 libv8-3.14.5
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
[ ok ] Restarting redis-server (via systemctl): redis-server.service.
Install Celery via supervisor...
[ ok ] Stopping supervisor (via systemctl): supervisor.service.
[ ok ] Starting supervisor (via systemctl): supervisor.service.
Checking the permissions for 
  File: ‘/dev/shm’
  Size: 60        	Blocks: 0          IO Block: 4096   directory
Device: 11h/17d	Inode: 657         Links: 2

I tried a lot on another server and i think at one point django is reinstall to anothe version which breaks the all thing. This log is from a fresh install.

I also try to run it using python manage.py runserver 

> raceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

What can i do ?

Thanks

**Comment by aurapalmer** [comment]
Same here.. I found that aggregates doesn't exist under sql in Django 1.10, but it does in 1.8.
In func_install_pip_deps the latest version of Django (so, 1.10) got installed, and despite any of my efforts to uninstall django and pip install django==1.8 manually, whenever I was getting to that fuction 1.10 kept getting installed.. so what I did as a workaround, since all the deps were already installed when I run the script the first time:
- cloned git django branch stable/1.8.x
- renamed /opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django to /opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/django.bk
- copied django git dir to /opt/miniconda/envs/cdr-stats/lib/python2.7/site-packages/
- commented out rm cdr-stats-functions.sh and wget --no-check-certificate https://raw.github.com/cdr-stats/cdr-stats/$BRANCH/install/cdr-stats-functions.sh -O cdr-stats-functions.sh in install-cdr-stats.sh
- commented out when the function func_install_pip_deps is called in cdr-stats-functions.sh
- run install-cdr-stats.sh again

it went past that bit, but I got these:

```
SystemCheckError: System check identified some issues:

ERRORS:
cdr.CDR.user: (fields.E306) The name 'Call Owner' is invalid related_name for field CDR.user
        HINT: Related name must be a valid Python identifier or end with a '+'
voip_billing.VoIPPlan_BanPlan.banplan: (fields.E306) The name 'ban plan' is invalid related_name for field VoIPPlan_BanPlan.banplan
        HINT: Related name must be a valid Python identifier or end with a '+'
voip_billing.VoIPPlan_BanPlan.voipplan: (fields.E306) The name 'voip plan' is invalid related_name for field VoIPPlan_BanPlan.voipplan
        HINT: Related name must be a valid Python identifier or end with a '+'
voip_billing.VoIPPlan_VoIPCarrierPlan.voipcarrierplan: (fields.E306) The name 'carrier plan' is invalid related_name for field VoIPPlan_VoIPCarrierPlan.voipcarrierplan
        HINT: Related name must be a valid Python identifier or end with a '+'
voip_billing.VoIPPlan_VoIPRetailPlan.voipplan: (fields.E306) The name 'VoIP Plan' is invalid related_name for field VoIPPlan_VoIPRetailPlan.voipplan
        HINT: Related name must be a valid Python identifier or end with a '+'
voip_billing.VoIPPlan_VoIPRetailPlan.voipretailplan: (fields.E306) The name 'VoIP Retail Plan' is invalid related_name for field VoIPPlan_VoIPRetailPlan.voipretailplan
        HINT: Related name must be a valid Python identifier or end with a '+'

```
It looks like totally unrelated to the aggregates issue anyway.
Now, I'm unable to test it at the moment cause nginx is throwing a 500 error (doh) and I haven't finished the switch part yet, but .. I hope it helps somehow, until a more authoritative answer comes through :)

A.

**Comment by areski** [comment]
I believe it should be fixed now with the last release 3.1.4 (https://github.com/cdr-stats/cdr-stats/commit/d1333bb1f274c4fbcfee7949e8b0b9312b6b1c97)
please try to reinstall and see how it goes.

**Comment by aurapalmer** [comment]
Yup, BTW my django 1.8 didn't work in the end.. didn't create the tables
so.. I ended up sedding the django-debug-toolbar line and replacing it with
1.3.3. Saw someone did a pull with 1.4 that also worked, good stuff. :)

**Comment by areski** [comment]
There is always a lot of effort needed to upgrade to the latest version of Django, unfortunately I don't have much time at the moment.

**Comment by aurapalmer** [comment]
1.7.7 works so.. it's just as good lol
